### ISSUE TITLE
Add database support

### ISSUE THREAD

**Issue by mogigoma** [tenable/pedant#4]
Implement SQLite database support with ActiveRecord, and include a 'db' command.

**Comment by alexwebr** [comment]
More tuning may be required, but after some experimentation my experience is that creating an AST from scratch every time is faster than marshalling/unmarshalling exported ASTs. Leaving open until I'm totally confident of that position.

**Comment by alexwebr** [comment]
I think this is a worthwhile project, not necessarily for performance reasons but because it could let us have codebase-wide checks for things like duplicate code.
